#FROM node:12.10.0-alpine

#WORKDIR /usr/app

#COPY package*.json ./
#RUN npm ci -qy
#RUN npm install

#COPY . .

#RUN npm build

#EXPOSE 3000
FROM node:10-alpine as builder

COPY package.json package-lock.json ./
RUN npm install && mkdir /react-frontend && mv ./node_modules ./react-frontend

WORKDIR /react-frontend

COPY . .

RUN npm run build


FROM nginx:1.16.0-alpine
COPY --from=builder /react-frontend/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]


